import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'features/games/presentation/memory_matching/screens/memory_game_menu_screen.dart';
import 'features/games/presentation/pattern_recognition/screens/pattern_game_menu_screen.dart';
import 'features/games/presentation/providers/database_provider.dart';
import 'features/games/presentation/shared/design_system/app_colors.dart';
import 'features/games/presentation/shared/design_system/app_dimensions.dart';
import 'features/games/presentation/shared/design_system/app_text_styles.dart';
import 'l10n/app_localizations.dart';

/// Application entry point.
///
/// [ProviderScope] at root — only one, never nested (except test overrides).
/// [_DatabasePrewarmObserver] eagerly opens the Drift DB so game screens load instantly.
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(
    ProviderScope(
      observers: const [_DatabasePrewarmObserver()],
      child: const CognitiveCareApp(),
    ),
  );
}

class CognitiveCareApp extends StatelessWidget {
  const CognitiveCareApp({super.key});

  @override
  Widget build(final BuildContext context) {
    return MaterialApp(
      title: 'Cognitive Care Games',
      debugShowCheckedModeBanner: false,
      // ── Localisation ──────────────────────────────────────────────────────
      // AppLocalizations is generated by `flutter gen-l10n` from lib/l10n/*.arb
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: AppLocalizations.supportedLocales,
      theme: _buildTheme(),
      home: const GameSelectionScreen(),
      routes: {
        MemoryGameMenuScreen.routeName: (_) => const MemoryGameMenuScreen(),
        PatternGameMenuScreen.routeName: (_) => const PatternGameMenuScreen(),
      },
    );
  }

  ThemeData _buildTheme() {
    return ThemeData(
      useMaterial3: true,
      colorScheme: const ColorScheme(
        brightness: Brightness.light,
        primary: AppColors.primary,
        onPrimary: AppColors.onPrimary,
        secondary: AppColors.secondary,
        onSecondary: AppColors.onSecondary,
        error: AppColors.error,
        onError: AppColors.onError,
        surface: AppColors.surface,
        onSurface: AppColors.textPrimary,
      ),
      scaffoldBackgroundColor: AppColors.background,
      textTheme: const TextTheme(
        displayLarge: AppTextStyles.displayLarge,
        headlineMedium: AppTextStyles.headlineMedium,
        headlineSmall: AppTextStyles.headlineSmall,
        bodyLarge: AppTextStyles.bodyLarge,
        bodyMedium: AppTextStyles.bodyMedium,
        labelLarge: AppTextStyles.labelLarge,
        labelMedium: AppTextStyles.labelMedium,
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          minimumSize: const Size(
            AppDimensions.buttonMinWidth,
            AppDimensions.buttonHeightPrimary,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(AppDimensions.buttonBorderRadius),
          ),
          textStyle: AppTextStyles.labelLarge,
        ),
      ),
      cardTheme: CardThemeData(
        elevation: AppDimensions.cardElevation,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(AppDimensions.cardBorderRadius),
        ),
        color: AppColors.surface,
      ),
    );
  }
}

/// Home screen — lets the user choose which game to play.
///
/// This screen is the entry point from the dashboard module.
/// When the dashboard team is ready, they replace this with their own
/// navigation and call [MemoryGameMenuScreen.routeName] or
/// [PatternGameMenuScreen.routeName] directly.
class GameSelectionScreen extends StatelessWidget {
  const GameSelectionScreen({super.key});

  @override
  Widget build(final BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: AppColors.primary,
        foregroundColor: AppColors.onPrimary,
        title: const Text(
          'Cognitive Care Games',
          style: AppTextStyles.headlineMedium,
        ),
        elevation: 0,
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(
            horizontal: AppDimensions.screenPaddingH,
            vertical: AppDimensions.screenPaddingV,
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const Text(
                'Choose a Game',
                style: AppTextStyles.displayLarge,
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: AppDimensions.spacingSmall),
              const Text(
                'Select a game to begin your session.',
                style: AppTextStyles.bodyLarge,
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: AppDimensions.spacingLarge),

              // ── Memory Matching card ──────────────────────────────────────
              _GameCard(
                title: 'Memory Matching',
                description:
                    'Flip cards and find matching pairs. Trains recall and focus.',
                icon: Icons.grid_view_rounded,
                onTap: () => Navigator.pushNamed(
                  context,
                  MemoryGameMenuScreen.routeName,
                ),
              ),

              const SizedBox(height: AppDimensions.spacingMedium),

              // ── Pattern Recognition card ──────────────────────────────────
              _GameCard(
                title: 'Pattern Recognition',
                description:
                    'Watch the pattern, choose what comes next. Trains logical thinking.',
                icon: Icons.pattern_rounded,
                onTap: () => Navigator.pushNamed(
                  context,
                  PatternGameMenuScreen.routeName,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _GameCard extends StatelessWidget {
  const _GameCard({
    required this.title,
    required this.description,
    required this.icon,
    required this.onTap,
  });

  final String title;
  final String description;
  final IconData icon;
  final VoidCallback onTap;

  @override
  Widget build(final BuildContext context) {
    return Semantics(
      button: true,
      label: title,
      child: Card(
        color: AppColors.surface,
        elevation: AppDimensions.cardElevation,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(AppDimensions.cardBorderRadius),
        ),
        child: InkWell(
          onTap: onTap,
          borderRadius: BorderRadius.circular(AppDimensions.cardBorderRadius),
          splashFactory: NoSplash.splashFactory,
          child: Padding(
            padding: const EdgeInsets.all(AppDimensions.spacingMedium),
            child: Row(
              children: [
                Container(
                  width: AppDimensions.touchTargetPreferred,
                  height: AppDimensions.touchTargetPreferred,
                  decoration: BoxDecoration(
                    color: AppColors.primary.withAlpha(20),
                    borderRadius: BorderRadius.circular(
                      AppDimensions.buttonBorderRadius,
                    ),
                  ),
                  child: Icon(
                    icon,
                    color: AppColors.primary,
                    size: AppDimensions.iconSizePrimary,
                  ),
                ),
                const SizedBox(width: AppDimensions.spacingMedium),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(title, style: AppTextStyles.headlineSmall),
                      const SizedBox(height: 4),
                      Text(description, style: AppTextStyles.bodyMedium),
                    ],
                  ),
                ),
                const Icon(
                  Icons.chevron_right_rounded,
                  color: AppColors.primary,
                  size: AppDimensions.iconSizePrimary,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

/// Pre-warms the database provider so game screens open without delay.
base class _DatabasePrewarmObserver extends ProviderObserver {
  const _DatabasePrewarmObserver();

  @override
  void didAddProvider(
    final ProviderObserverContext context,
    final Object? value,
  ) {
    if (context.provider == databaseProvider) {
      context.container.read(databaseProvider.future).ignore();
    }
  }
}
