import 'package:cognitive_care_games/features/games/domain/entities/game_session.dart';
import 'package:cognitive_care_games/features/games/domain/repositories/i_game_session_repository.dart';
import 'package:cognitive_care_games/features/games/domain/value_objects/difficulty.dart';
import 'package:cognitive_care_games/features/games/domain/value_objects/game_type.dart';
import 'package:cognitive_care_games/features/games/domain/value_objects/session_status.dart';
import 'package:cognitive_care_games/features/games/domain/value_objects/sync_status.dart';

/// Use-case: creates and persists a new [GameSession].
///
/// Called by [SessionNotifier] when the player taps "Start".
/// Returns the persisted [GameSession] so the caller has the id
/// for subsequent metric capture.
///
/// Throws [DomainException] if [sessionId] is empty or [gameType]/[difficulty]
/// are invalid (should never occur from validated UI — guards defensive correctness).
final class StartGameSession {
  const StartGameSession(this._sessionRepository);

  final IGameSessionRepository _sessionRepository;

  /// Creates a [GameSession] from the given parameters, persists it,
  /// and returns it.
  ///
  /// [sessionId] must be a pre-generated UUID v4 (generated by the caller
  /// so the ID is known before the async persistence completes).
  Future<GameSession> execute({
    required String sessionId,
    required GameType gameType,
    required Difficulty difficulty,
  }) async {
    if (sessionId.trim().isEmpty) {
      throw const DomainException('Session id must not be empty.');
    }

    final now = DateTime.now().millisecondsSinceEpoch;
    final session = GameSession(
      id: sessionId,
      gameType: gameType,
      difficulty: difficulty,
      startTime: now,
      status: SessionStatus.inProgress,
      syncStatus: SyncStatus.unsynced,
    );

    await _sessionRepository.save(session);
    return session;
  }
}

/// End-game session use-case: transitions a session to a terminal status
/// and records the end time.
///
/// Called by [SessionNotifier] when the game ends (win, time-out, or quit).
final class EndGameSession {
  const EndGameSession(this._sessionRepository);

  final IGameSessionRepository _sessionRepository;

  /// Updates the session identified by [sessionId] with:
  ///   - [endTime] = [endTimeMs] (or now if null)
  ///   - [status] = [finalStatus]
  ///
  /// [finalStatus] must be a terminal state ([completed] or [abandoned]).
  /// Throws [DomainException] for non-terminal status or unknown session id.
  Future<GameSession> execute({
    required String sessionId,
    required SessionStatus finalStatus,
    int? endTimeMs,
  }) async {
    if (sessionId.trim().isEmpty) {
      throw const DomainException('Session id must not be empty.');
    }
    if (!finalStatus.isTerminal) {
      throw DomainException(
        'EndGameSession requires a terminal status. Got: ${finalStatus.value}',
      );
    }

    final existing = await _sessionRepository.getById(sessionId);
    if (existing == null) {
      throw DomainException('Session not found: $sessionId');
    }

    final updated = existing.copyWith(
      endTime: endTimeMs ?? DateTime.now().millisecondsSinceEpoch,
      status: finalStatus,
    );

    await _sessionRepository.update(updated);
    return updated;
  }
}

/// Domain-layer exception.
///
/// Thrown by use-cases when invariants are violated. Callers (Riverpod
/// notifiers) catch this and convert it to appropriate UI error states.
final class DomainException implements Exception {
  const DomainException(this.message);

  final String message;

  @override
  String toString() => 'DomainException: $message';
}
