// Mocks generated by Mockito from annotations
// in cognitive_care_games/test/features/games/domain/usecases/start_game_session_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:cognitive_care_games/features/games/domain/entities/game_session.dart'
    as _i4;
import 'package:cognitive_care_games/features/games/domain/repositories/i_game_session_repository.dart'
    as _i2;
import 'package:cognitive_care_games/features/games/domain/value_objects/game_type.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IGameSessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGameSessionRepository extends _i1.Mock
    implements _i2.IGameSessionRepository {
  MockIGameSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> save(_i4.GameSession? session) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [session],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> update(_i4.GameSession? session) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [session],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.GameSession?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i3.Future<_i4.GameSession?>.value(),
      ) as _i3.Future<_i4.GameSession?>);

  @override
  _i3.Future<List<_i4.GameSession>> getByGame(_i5.GameType? gameType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByGame,
          [gameType],
        ),
        returnValue:
            _i3.Future<List<_i4.GameSession>>.value(<_i4.GameSession>[]),
      ) as _i3.Future<List<_i4.GameSession>>);

  @override
  _i3.Future<List<_i4.GameSession>> getPendingSessions() => (super.noSuchMethod(
        Invocation.method(
          #getPendingSessions,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.GameSession>>.value(<_i4.GameSession>[]),
      ) as _i3.Future<List<_i4.GameSession>>);

  @override
  _i3.Future<void> markSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markSynced,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> markSyncFailed(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markSyncFailed,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
